/// <reference path="./sanity.types.ts" />
// Query result types are generated by `pnpm --filter @owambe/studio typegen`.
// Loads @sanity/client so TypeGen's module augmentation in sanity.types.ts resolves.
import type {} from '@sanity/client'
import {defineQuery} from 'groq'

export const EVENT_QUERY = defineQuery(`
  *[_type == "event"] | order(date asc)[0]{
    _id,
    title,
    date,
    venue,
    city,
    status,
    colours[]{_key, name, hex, side},
    "couple": couple[]->{_id, name, side}
  }
`)
