/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Measurements = {
  _type: "measurements";
  bust?: number;
  waist?: number;
  hips?: number;
  length?: number;
  style?: string;
};

export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type InviteTranslation = {
  _type: "inviteTranslation";
  language?: "yo" | "ig" | "pcm";
  text?: string;
  reviewed?: boolean;
  reviewedBy?: PersonReference;
};

export type NonNegotiable = {
  _type: "nonNegotiable";
  requirement?: string;
  reason?: string;
};

export type AsoEbiColour = {
  _type: "asoEbiColour";
  name?: string;
  hex?: string;
  side?: "bride" | "groom" | "both";
};

export type Money = {
  _type: "money";
  amount?: string;
  currency?: "NGN";
};

export type AsoEbiLotReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "asoEbiLot";
};

export type GuestReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "guest";
};

export type AsoEbiOrder = {
  _id: string;
  _type: "asoEbiOrder";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  lot?: AsoEbiLotReference;
  guest?: GuestReference;
  quantity?: number;
  amount?: Money;
  bachsCheckoutSessionId?: string;
  bachsPaymentId?: string;
  paidAt?: string;
  measurements?: Measurements;
};

export type EventReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "event";
};

export type Guest = {
  _id: string;
  _type: "guest";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  person?: PersonReference;
  event?: EventReference;
  inviteCode?: string;
  seats?: number;
  table?: string;
  rsvp?: "pending" | "attending" | "declined";
  checkedInAt?: string;
};

export type VendorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "vendor";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type AsoEbiLot = {
  _id: string;
  _type: "asoEbiLot";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  event?: EventReference;
  colourName?: string;
  fabricType?: "asoOke" | "lace" | "george" | "ankara" | "gele";
  unit?: string;
  price?: Money;
  stock?: number;
  tailor?: VendorReference;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Vendor = {
  _id: string;
  _type: "vendor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  category?:
    "caterer" | "dj" | "band" | "mc" | "tailor" | "photographer" | "decor";
  contact?: PersonReference;
  event?: EventReference;
  arrivedAt?: string;
};

export type ProgramItem = {
  _id: string;
  _type: "programItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  plannedStart?: string;
  plannedDuration?: number;
  owner?: PersonReference;
  sideOfInterest?: "bride" | "groom" | "both";
  notes?: string;
  actualStart?: string;
  actualEnd?: string;
};

export type ProgramItemReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "programItem";
};

export type ProgramOfEvents = {
  _id: string;
  _type: "programOfEvents";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  event?: EventReference;
  items?: Array<
    {
      _key: string;
    } & ProgramItemReference
  >;
  version?: number;
  brief?: string;
};

export type FamilySide = {
  _id: string;
  _type: "familySide";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  event?: EventReference;
  side?: "bride" | "groom";
  approvers?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  nonNegotiables?: Array<
    {
      _key: string;
    } & NonNegotiable
  >;
  notes?: string;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  phone?: string;
  side?: "bride" | "groom" | "couple" | "neutral";
  role?:
    | "celebrant"
    | "parent"
    | "elder"
    | "coordinator"
    | "mc"
    | "vendorContact"
    | "guest";
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  couple?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  date?: string;
  venue?: {
    name?: string;
    address?: string;
  };
  city?: string;
  colours?: Array<
    {
      _key: string;
    } & AsoEbiColour
  >;
  status?: "planning" | "finalWeek" | "live" | "concluded";
  inviteMessage?: string;
  inviteTranslations?: Array<
    {
      _key: string;
    } & InviteTranslation
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | Measurements
  | PersonReference
  | InviteTranslation
  | NonNegotiable
  | AsoEbiColour
  | Money
  | AsoEbiLotReference
  | GuestReference
  | AsoEbiOrder
  | EventReference
  | Guest
  | VendorReference
  | SanityImageAssetReference
  | AsoEbiLot
  | SanityImageCrop
  | SanityImageHotspot
  | Vendor
  | ProgramItem
  | ProgramItemReference
  | ProgramOfEvents
  | FamilySide
  | Person
  | Event
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: ../packages/shared/src/queries.ts
// Variable: EVENT_QUERY
// Query: *[_type == "event"] | order(date asc)[0]{    _id,    title,    date,    venue,    city,    status,    colours[]{_key, name, hex, side},    "couple": couple[]->{_id, name, side}  }
export type EVENT_QUERY_RESULT = {
  _id: string;
  title: string | null;
  date: string | null;
  venue: {
    name?: string;
    address?: string;
  } | null;
  city: string | null;
  status: "concluded" | "finalWeek" | "live" | "planning" | null;
  colours: Array<{
    _key: string;
    name: string | null;
    hex: string | null;
    side: "both" | "bride" | "groom" | null;
  }> | null;
  couple: Array<{
    _id: string;
    name: string | null;
    side: "bride" | "couple" | "groom" | "neutral" | null;
  }> | null;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "event"] | order(date asc)[0]{\n    _id,\n    title,\n    date,\n    venue,\n    city,\n    status,\n    colours[]{_key, name, hex, side},\n    "couple": couple[]->{_id, name, side}\n  }\n': EVENT_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
